baseurl = "http://www.nathanbibb.com"
title = "Nathan Bibb"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
pluralizelisttitles = false
# pygmentsCodefences = true
pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[params]
    author = "Nathan Bibb"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Hi, there!  I'm Nathan.  I work for a company that sells software to insurance companies (and much more). I also enjoy music, games, technology, history, and pensively worrying about things.
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "journal"
    # name = "Journal" #If display text link, cancel comment out
    pre = "<i class='fas fa-book fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/journal/"
    weight = 10

[[menu.main]]
    identifier = "facebook"
    # name = "Twitter"
    pre = "<i class='fab fa-facebook fa-lg'></i>"
    url = "https://www.facebook.com/nathanbibb"
    weight = 20

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/nathanbibb"
    weight = 20

[[menu.main]]
    identifier = "linkedin"
    # name = "GitHub"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/nathanbibb/"
    weight = 30

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/nathanbibb"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:contact@nathanbibb.com"
    weight = 40
    
[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "nbcom"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://www.nathanbibb.com"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>


# ... add more [[deployment.targets]] sections ...


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
